//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProjectTm.EppmWs.CalendarService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CalendarPortBinding", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class CalendarService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateCalendarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadCalendarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCalendarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCalendarsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CalendarService() {
            this.Url = global::ProjectTm.Properties.Settings.Default.ProjectTm_EppmWs_CalendarService_CalendarService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCalendarsCompletedEventHandler CreateCalendarsCompleted;
        
        /// <remarks/>
        public event ReadCalendarsCompletedEventHandler ReadCalendarsCompleted;
        
        /// <remarks/>
        public event UpdateCalendarsCompletedEventHandler UpdateCalendarsCompleted;
        
        /// <remarks/>
        public event DeleteCalendarsCompletedEventHandler DeleteCalendarsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateCalendars", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CreateCalendarsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ObjectId", IsNullable=false)]
        public int[] CreateCalendars([System.Xml.Serialization.XmlArrayAttribute("CreateCalendars", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Calendar[] CreateCalendars1) {
            object[] results = this.Invoke("CreateCalendars", new object[] {
                        CreateCalendars1});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateCalendarsAsync(Calendar[] CreateCalendars1) {
            this.CreateCalendarsAsync(CreateCalendars1, null);
        }
        
        /// <remarks/>
        public void CreateCalendarsAsync(Calendar[] CreateCalendars1, object userState) {
            if ((this.CreateCalendarsOperationCompleted == null)) {
                this.CreateCalendarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCalendarsOperationCompleted);
            }
            this.InvokeAsync("CreateCalendars", new object[] {
                        CreateCalendars1}, this.CreateCalendarsOperationCompleted, userState);
        }
        
        private void OnCreateCalendarsOperationCompleted(object arg) {
            if ((this.CreateCalendarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCalendarsCompleted(this, new CreateCalendarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReadCalendars", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadCalendarsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Calendar[] ReadCalendars([System.Xml.Serialization.XmlElementAttribute("ReadCalendars", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")] ReadCalendars ReadCalendars1) {
            object[] results = this.Invoke("ReadCalendars", new object[] {
                        ReadCalendars1});
            return ((Calendar[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadCalendarsAsync(ReadCalendars ReadCalendars1) {
            this.ReadCalendarsAsync(ReadCalendars1, null);
        }
        
        /// <remarks/>
        public void ReadCalendarsAsync(ReadCalendars ReadCalendars1, object userState) {
            if ((this.ReadCalendarsOperationCompleted == null)) {
                this.ReadCalendarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadCalendarsOperationCompleted);
            }
            this.InvokeAsync("ReadCalendars", new object[] {
                        ReadCalendars1}, this.ReadCalendarsOperationCompleted, userState);
        }
        
        private void OnReadCalendarsOperationCompleted(object arg) {
            if ((this.ReadCalendarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCalendarsCompleted(this, new ReadCalendarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateCalendars", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateCalendarsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
        public UpdateCalendarsResponse UpdateCalendars([System.Xml.Serialization.XmlElementAttribute("UpdateCalendars", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")] UpdateCalendars UpdateCalendars1) {
            object[] results = this.Invoke("UpdateCalendars", new object[] {
                        UpdateCalendars1});
            return ((UpdateCalendarsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCalendarsAsync(UpdateCalendars UpdateCalendars1) {
            this.UpdateCalendarsAsync(UpdateCalendars1, null);
        }
        
        /// <remarks/>
        public void UpdateCalendarsAsync(UpdateCalendars UpdateCalendars1, object userState) {
            if ((this.UpdateCalendarsOperationCompleted == null)) {
                this.UpdateCalendarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCalendarsOperationCompleted);
            }
            this.InvokeAsync("UpdateCalendars", new object[] {
                        UpdateCalendars1}, this.UpdateCalendarsOperationCompleted, userState);
        }
        
        private void OnUpdateCalendarsOperationCompleted(object arg) {
            if ((this.UpdateCalendarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCalendarsCompleted(this, new UpdateCalendarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteCalendars", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteCalendarsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
        public DeleteCalendarsResponse DeleteCalendars([System.Xml.Serialization.XmlElementAttribute("DeleteCalendars", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")] DeleteCalendars DeleteCalendars1) {
            object[] results = this.Invoke("DeleteCalendars", new object[] {
                        DeleteCalendars1});
            return ((DeleteCalendarsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCalendarsAsync(DeleteCalendars DeleteCalendars1) {
            this.DeleteCalendarsAsync(DeleteCalendars1, null);
        }
        
        /// <remarks/>
        public void DeleteCalendarsAsync(DeleteCalendars DeleteCalendars1, object userState) {
            if ((this.DeleteCalendarsOperationCompleted == null)) {
                this.DeleteCalendarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCalendarsOperationCompleted);
            }
            this.InvokeAsync("DeleteCalendars", new object[] {
                        DeleteCalendars1}, this.DeleteCalendarsOperationCompleted, userState);
        }
        
        private void OnDeleteCalendarsOperationCompleted(object arg) {
            if ((this.DeleteCalendarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCalendarsCompleted(this, new DeleteCalendarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class Calendar {
        
        private System.Nullable<int> baseCalendarObjectIdField;
        
        private bool baseCalendarObjectIdFieldSpecified;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private bool createDateFieldSpecified;
        
        private string createUserField;
        
        private double hoursPerDayField;
        
        private bool hoursPerDayFieldSpecified;
        
        private double hoursPerMonthField;
        
        private bool hoursPerMonthFieldSpecified;
        
        private double hoursPerWeekField;
        
        private bool hoursPerWeekFieldSpecified;
        
        private double hoursPerYearField;
        
        private bool hoursPerYearFieldSpecified;
        
        private System.Nullable<bool> isBaselineField;
        
        private bool isBaselineFieldSpecified;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private bool isPersonalField;
        
        private bool isPersonalFieldSpecified;
        
        private bool isTemplateField;
        
        private bool isTemplateFieldSpecified;
        
        private System.Nullable<System.DateTime> lastUpdateDateField;
        
        private bool lastUpdateDateFieldSpecified;
        
        private string lastUpdateUserField;
        
        private string nameField;
        
        private int objectIdField;
        
        private bool objectIdFieldSpecified;
        
        private string projectIdField;
        
        private System.Nullable<int> projectObjectIdField;
        
        private bool projectObjectIdFieldSpecified;
        
        private CalendarType typeField;
        
        private bool typeFieldSpecified;
        
        private CalendarStandardWorkHours[] standardWorkWeekField;
        
        private CalendarHolidayOrException[] holidayOrExceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BaseCalendarObjectId {
            get {
                return this.baseCalendarObjectIdField;
            }
            set {
                this.baseCalendarObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaseCalendarObjectIdSpecified {
            get {
                return this.baseCalendarObjectIdFieldSpecified;
            }
            set {
                this.baseCalendarObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public double HoursPerDay {
            get {
                return this.hoursPerDayField;
            }
            set {
                this.hoursPerDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursPerDaySpecified {
            get {
                return this.hoursPerDayFieldSpecified;
            }
            set {
                this.hoursPerDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double HoursPerMonth {
            get {
                return this.hoursPerMonthField;
            }
            set {
                this.hoursPerMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursPerMonthSpecified {
            get {
                return this.hoursPerMonthFieldSpecified;
            }
            set {
                this.hoursPerMonthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double HoursPerWeek {
            get {
                return this.hoursPerWeekField;
            }
            set {
                this.hoursPerWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursPerWeekSpecified {
            get {
                return this.hoursPerWeekFieldSpecified;
            }
            set {
                this.hoursPerWeekFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double HoursPerYear {
            get {
                return this.hoursPerYearField;
            }
            set {
                this.hoursPerYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoursPerYearSpecified {
            get {
                return this.hoursPerYearFieldSpecified;
            }
            set {
                this.hoursPerYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsBaseline {
            get {
                return this.isBaselineField;
            }
            set {
                this.isBaselineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBaselineSpecified {
            get {
                return this.isBaselineFieldSpecified;
            }
            set {
                this.isBaselineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDefaultSpecified {
            get {
                return this.isDefaultFieldSpecified;
            }
            set {
                this.isDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsPersonal {
            get {
                return this.isPersonalField;
            }
            set {
                this.isPersonalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPersonalSpecified {
            get {
                return this.isPersonalFieldSpecified;
            }
            set {
                this.isPersonalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsTemplate {
            get {
                return this.isTemplateField;
            }
            set {
                this.isTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTemplateSpecified {
            get {
                return this.isTemplateFieldSpecified;
            }
            set {
                this.isTemplateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdateDateSpecified {
            get {
                return this.lastUpdateDateFieldSpecified;
            }
            set {
                this.lastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdateUser {
            get {
                return this.lastUpdateUserField;
            }
            set {
                this.lastUpdateUserField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObjectIdSpecified {
            get {
                return this.objectIdFieldSpecified;
            }
            set {
                this.objectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProjectObjectId {
            get {
                return this.projectObjectIdField;
            }
            set {
                this.projectObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectObjectIdSpecified {
            get {
                return this.projectObjectIdFieldSpecified;
            }
            set {
                this.projectObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CalendarType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StandardWorkHours", IsNullable=false)]
        public CalendarStandardWorkHours[] StandardWorkWeek {
            get {
                return this.standardWorkWeekField;
            }
            set {
                this.standardWorkWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HolidayOrException", IsNullable=false)]
        public CalendarHolidayOrException[] HolidayOrExceptions {
            get {
                return this.holidayOrExceptionsField;
            }
            set {
                this.holidayOrExceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public enum CalendarType {
        
        /// <remarks/>
        Global,
        
        /// <remarks/>
        Project,
        
        /// <remarks/>
        Resource,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class CalendarStandardWorkHours {
        
        private CalendarStandardWorkHoursDayOfWeek dayOfWeekField;
        
        private CalendarStandardWorkHoursWorkTime[] workTimeField;
        
        /// <remarks/>
        public CalendarStandardWorkHoursDayOfWeek DayOfWeek {
            get {
                return this.dayOfWeekField;
            }
            set {
                this.dayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkTime")]
        public CalendarStandardWorkHoursWorkTime[] WorkTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public enum CalendarStandardWorkHoursDayOfWeek {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class CalendarStandardWorkHoursWorkTime {
        
        private System.DateTime finishField;
        
        private System.DateTime startField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Finish {
            get {
                return this.finishField;
            }
            set {
                this.finishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class DeleteCalendarsResponse {
        
        private bool returnField;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class DeleteCalendars {
        
        private int[] objectIdField;
        
        private DeleteCalendarsDeleteWithReplacement[] deleteWithReplacementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectId")]
        public int[] ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeleteWithReplacement")]
        public DeleteCalendarsDeleteWithReplacement[] DeleteWithReplacement {
            get {
                return this.deleteWithReplacementField;
            }
            set {
                this.deleteWithReplacementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class DeleteCalendarsDeleteWithReplacement {
        
        private int[] objectIdField;
        
        private int replacementObjectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectId")]
        public int[] ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        public int ReplacementObjectId {
            get {
                return this.replacementObjectIdField;
            }
            set {
                this.replacementObjectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class UpdateCalendarsResponse {
        
        private bool returnField;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class UpdateCalendars {
        
        private bool replaceHolidayOrExceptionsField;
        
        private bool replaceHolidayOrExceptionsFieldSpecified;
        
        private Calendar[] calendarField;
        
        /// <remarks/>
        public bool ReplaceHolidayOrExceptions {
            get {
                return this.replaceHolidayOrExceptionsField;
            }
            set {
                this.replaceHolidayOrExceptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplaceHolidayOrExceptionsSpecified {
            get {
                return this.replaceHolidayOrExceptionsFieldSpecified;
            }
            set {
                this.replaceHolidayOrExceptionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Calendar")]
        public Calendar[] Calendar {
            get {
                return this.calendarField;
            }
            set {
                this.calendarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class ReadCalendars {
        
        private CalendarFieldType[] fieldField;
        
        private string filterField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public CalendarFieldType[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public enum CalendarFieldType {
        
        /// <remarks/>
        BaseCalendarObjectId,
        
        /// <remarks/>
        CreateDate,
        
        /// <remarks/>
        CreateUser,
        
        /// <remarks/>
        HolidayOrExceptions,
        
        /// <remarks/>
        HoursPerDay,
        
        /// <remarks/>
        HoursPerMonth,
        
        /// <remarks/>
        HoursPerWeek,
        
        /// <remarks/>
        HoursPerYear,
        
        /// <remarks/>
        IsBaseline,
        
        /// <remarks/>
        IsDefault,
        
        /// <remarks/>
        IsPersonal,
        
        /// <remarks/>
        IsTemplate,
        
        /// <remarks/>
        LastUpdateDate,
        
        /// <remarks/>
        LastUpdateUser,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        ObjectId,
        
        /// <remarks/>
        ProjectId,
        
        /// <remarks/>
        ProjectObjectId,
        
        /// <remarks/>
        StandardWorkWeek,
        
        /// <remarks/>
        Type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class CalendarHolidayOrException {
        
        private System.DateTime dateField;
        
        private CalendarHolidayOrExceptionWorkTime[] workTimeField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkTime")]
        public CalendarHolidayOrExceptionWorkTime[] WorkTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Calendar/V1")]
    public partial class CalendarHolidayOrExceptionWorkTime {
        
        private System.DateTime finishField;
        
        private System.DateTime startField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Finish {
            get {
                return this.finishField;
            }
            set {
                this.finishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateCalendarsCompletedEventHandler(object sender, CreateCalendarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCalendarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCalendarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadCalendarsCompletedEventHandler(object sender, ReadCalendarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCalendarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCalendarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Calendar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Calendar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateCalendarsCompletedEventHandler(object sender, UpdateCalendarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCalendarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCalendarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateCalendarsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCalendarsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteCalendarsCompletedEventHandler(object sender, DeleteCalendarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCalendarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCalendarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteCalendarsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteCalendarsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591