//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProjectTm.EppmWs.DepService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RelationshipPortBinding", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public partial class RelationshipService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateRelationshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadRelationshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRelationshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRelationshipsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RelationshipService() {
            this.Url = global::ProjectTm.Properties.Settings.Default.ProjectTm_EppmWs_DepService_RelationshipService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateRelationshipsCompletedEventHandler CreateRelationshipsCompleted;
        
        /// <remarks/>
        public event ReadRelationshipsCompletedEventHandler ReadRelationshipsCompleted;
        
        /// <remarks/>
        public event UpdateRelationshipsCompletedEventHandler UpdateRelationshipsCompleted;
        
        /// <remarks/>
        public event DeleteRelationshipsCompletedEventHandler DeleteRelationshipsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CreateRelationshipsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ObjectId", IsNullable=false)]
        public int[] CreateRelationships([System.Xml.Serialization.XmlArrayAttribute("CreateRelationships", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Relationship[] CreateRelationships1) {
            object[] results = this.Invoke("CreateRelationships", new object[] {
                        CreateRelationships1});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateRelationshipsAsync(Relationship[] CreateRelationships1) {
            this.CreateRelationshipsAsync(CreateRelationships1, null);
        }
        
        /// <remarks/>
        public void CreateRelationshipsAsync(Relationship[] CreateRelationships1, object userState) {
            if ((this.CreateRelationshipsOperationCompleted == null)) {
                this.CreateRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRelationshipsOperationCompleted);
            }
            this.InvokeAsync("CreateRelationships", new object[] {
                        CreateRelationships1}, this.CreateRelationshipsOperationCompleted, userState);
        }
        
        private void OnCreateRelationshipsOperationCompleted(object arg) {
            if ((this.CreateRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRelationshipsCompleted(this, new CreateRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReadRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadRelationshipsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Relationship[] ReadRelationships([System.Xml.Serialization.XmlElementAttribute("ReadRelationships", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")] ReadRelationships ReadRelationships1) {
            object[] results = this.Invoke("ReadRelationships", new object[] {
                        ReadRelationships1});
            return ((Relationship[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadRelationshipsAsync(ReadRelationships ReadRelationships1) {
            this.ReadRelationshipsAsync(ReadRelationships1, null);
        }
        
        /// <remarks/>
        public void ReadRelationshipsAsync(ReadRelationships ReadRelationships1, object userState) {
            if ((this.ReadRelationshipsOperationCompleted == null)) {
                this.ReadRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadRelationshipsOperationCompleted);
            }
            this.InvokeAsync("ReadRelationships", new object[] {
                        ReadRelationships1}, this.ReadRelationshipsOperationCompleted, userState);
        }
        
        private void OnReadRelationshipsOperationCompleted(object arg) {
            if ((this.ReadRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadRelationshipsCompleted(this, new ReadRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("UpdateRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateRelationshipsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
        public UpdateRelationshipsResponse UpdateRelationships([System.Xml.Serialization.XmlArrayAttribute("UpdateRelationships", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Relationship[] UpdateRelationships1) {
            object[] results = this.Invoke("UpdateRelationships", new object[] {
                        UpdateRelationships1});
            return ((UpdateRelationshipsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRelationshipsAsync(Relationship[] UpdateRelationships1) {
            this.UpdateRelationshipsAsync(UpdateRelationships1, null);
        }
        
        /// <remarks/>
        public void UpdateRelationshipsAsync(Relationship[] UpdateRelationships1, object userState) {
            if ((this.UpdateRelationshipsOperationCompleted == null)) {
                this.UpdateRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRelationshipsOperationCompleted);
            }
            this.InvokeAsync("UpdateRelationships", new object[] {
                        UpdateRelationships1}, this.UpdateRelationshipsOperationCompleted, userState);
        }
        
        private void OnUpdateRelationshipsOperationCompleted(object arg) {
            if ((this.UpdateRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRelationshipsCompleted(this, new UpdateRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DeleteRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteRelationshipsResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
        public DeleteRelationshipsResponse DeleteRelationships([System.Xml.Serialization.XmlArrayAttribute("DeleteRelationships", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")] [System.Xml.Serialization.XmlArrayItemAttribute("ObjectId", IsNullable=false)] int[] DeleteRelationships1) {
            object[] results = this.Invoke("DeleteRelationships", new object[] {
                        DeleteRelationships1});
            return ((DeleteRelationshipsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRelationshipsAsync(int[] DeleteRelationships1) {
            this.DeleteRelationshipsAsync(DeleteRelationships1, null);
        }
        
        /// <remarks/>
        public void DeleteRelationshipsAsync(int[] DeleteRelationships1, object userState) {
            if ((this.DeleteRelationshipsOperationCompleted == null)) {
                this.DeleteRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRelationshipsOperationCompleted);
            }
            this.InvokeAsync("DeleteRelationships", new object[] {
                        DeleteRelationships1}, this.DeleteRelationshipsOperationCompleted, userState);
        }
        
        private void OnDeleteRelationshipsOperationCompleted(object arg) {
            if ((this.DeleteRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRelationshipsCompleted(this, new DeleteRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public partial class Relationship {
        
        private System.Nullable<System.DateTime> arefField;
        
        private bool arefFieldSpecified;
        
        private System.Nullable<System.DateTime> arlsField;
        
        private bool arlsFieldSpecified;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private bool createDateFieldSpecified;
        
        private string createUserField;
        
        private bool isPredecessorBaselineField;
        
        private bool isPredecessorBaselineFieldSpecified;
        
        private bool isPredecessorTemplateField;
        
        private bool isPredecessorTemplateFieldSpecified;
        
        private bool isSuccessorBaselineField;
        
        private bool isSuccessorBaselineFieldSpecified;
        
        private bool isSuccessorTemplateField;
        
        private bool isSuccessorTemplateFieldSpecified;
        
        private System.Nullable<double> lagField;
        
        private bool lagFieldSpecified;
        
        private System.Nullable<System.DateTime> lastUpdateDateField;
        
        private bool lastUpdateDateFieldSpecified;
        
        private string lastUpdateUserField;
        
        private int objectIdField;
        
        private bool objectIdFieldSpecified;
        
        private string predecessorActivityIdField;
        
        private string predecessorActivityNameField;
        
        private int predecessorActivityObjectIdField;
        
        private bool predecessorActivityObjectIdFieldSpecified;
        
        private RelationshipPredecessorActivityType predecessorActivityTypeField;
        
        private bool predecessorActivityTypeFieldSpecified;
        
        private System.DateTime predecessorFinishDateField;
        
        private bool predecessorFinishDateFieldSpecified;
        
        private string predecessorProjectIdField;
        
        private System.Nullable<int> predecessorProjectObjectIdField;
        
        private bool predecessorProjectObjectIdFieldSpecified;
        
        private System.DateTime predecessorStartDateField;
        
        private bool predecessorStartDateFieldSpecified;
        
        private string predecessorWbsNameField;
        
        private string successorActivityIdField;
        
        private string successorActivityNameField;
        
        private int successorActivityObjectIdField;
        
        private bool successorActivityObjectIdFieldSpecified;
        
        private RelationshipSuccessorActivityType successorActivityTypeField;
        
        private bool successorActivityTypeFieldSpecified;
        
        private System.DateTime successorFinishDateField;
        
        private bool successorFinishDateFieldSpecified;
        
        private string successorProjectIdField;
        
        private System.Nullable<int> successorProjectObjectIdField;
        
        private bool successorProjectObjectIdFieldSpecified;
        
        private System.DateTime successorStartDateField;
        
        private bool successorStartDateFieldSpecified;
        
        private string successorWbsNameField;
        
        private RelationshipType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Aref {
            get {
                return this.arefField;
            }
            set {
                this.arefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArefSpecified {
            get {
                return this.arefFieldSpecified;
            }
            set {
                this.arefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Arls {
            get {
                return this.arlsField;
            }
            set {
                this.arlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArlsSpecified {
            get {
                return this.arlsFieldSpecified;
            }
            set {
                this.arlsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPredecessorBaseline {
            get {
                return this.isPredecessorBaselineField;
            }
            set {
                this.isPredecessorBaselineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPredecessorBaselineSpecified {
            get {
                return this.isPredecessorBaselineFieldSpecified;
            }
            set {
                this.isPredecessorBaselineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsPredecessorTemplate {
            get {
                return this.isPredecessorTemplateField;
            }
            set {
                this.isPredecessorTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPredecessorTemplateSpecified {
            get {
                return this.isPredecessorTemplateFieldSpecified;
            }
            set {
                this.isPredecessorTemplateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccessorBaseline {
            get {
                return this.isSuccessorBaselineField;
            }
            set {
                this.isSuccessorBaselineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSuccessorBaselineSpecified {
            get {
                return this.isSuccessorBaselineFieldSpecified;
            }
            set {
                this.isSuccessorBaselineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccessorTemplate {
            get {
                return this.isSuccessorTemplateField;
            }
            set {
                this.isSuccessorTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSuccessorTemplateSpecified {
            get {
                return this.isSuccessorTemplateFieldSpecified;
            }
            set {
                this.isSuccessorTemplateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Lag {
            get {
                return this.lagField;
            }
            set {
                this.lagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LagSpecified {
            get {
                return this.lagFieldSpecified;
            }
            set {
                this.lagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdateDateSpecified {
            get {
                return this.lastUpdateDateFieldSpecified;
            }
            set {
                this.lastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdateUser {
            get {
                return this.lastUpdateUserField;
            }
            set {
                this.lastUpdateUserField = value;
            }
        }
        
        /// <remarks/>
        public int ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObjectIdSpecified {
            get {
                return this.objectIdFieldSpecified;
            }
            set {
                this.objectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PredecessorActivityId {
            get {
                return this.predecessorActivityIdField;
            }
            set {
                this.predecessorActivityIdField = value;
            }
        }
        
        /// <remarks/>
        public string PredecessorActivityName {
            get {
                return this.predecessorActivityNameField;
            }
            set {
                this.predecessorActivityNameField = value;
            }
        }
        
        /// <remarks/>
        public int PredecessorActivityObjectId {
            get {
                return this.predecessorActivityObjectIdField;
            }
            set {
                this.predecessorActivityObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorActivityObjectIdSpecified {
            get {
                return this.predecessorActivityObjectIdFieldSpecified;
            }
            set {
                this.predecessorActivityObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RelationshipPredecessorActivityType PredecessorActivityType {
            get {
                return this.predecessorActivityTypeField;
            }
            set {
                this.predecessorActivityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorActivityTypeSpecified {
            get {
                return this.predecessorActivityTypeFieldSpecified;
            }
            set {
                this.predecessorActivityTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PredecessorFinishDate {
            get {
                return this.predecessorFinishDateField;
            }
            set {
                this.predecessorFinishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorFinishDateSpecified {
            get {
                return this.predecessorFinishDateFieldSpecified;
            }
            set {
                this.predecessorFinishDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PredecessorProjectId {
            get {
                return this.predecessorProjectIdField;
            }
            set {
                this.predecessorProjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PredecessorProjectObjectId {
            get {
                return this.predecessorProjectObjectIdField;
            }
            set {
                this.predecessorProjectObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorProjectObjectIdSpecified {
            get {
                return this.predecessorProjectObjectIdFieldSpecified;
            }
            set {
                this.predecessorProjectObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PredecessorStartDate {
            get {
                return this.predecessorStartDateField;
            }
            set {
                this.predecessorStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PredecessorStartDateSpecified {
            get {
                return this.predecessorStartDateFieldSpecified;
            }
            set {
                this.predecessorStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PredecessorWbsName {
            get {
                return this.predecessorWbsNameField;
            }
            set {
                this.predecessorWbsNameField = value;
            }
        }
        
        /// <remarks/>
        public string SuccessorActivityId {
            get {
                return this.successorActivityIdField;
            }
            set {
                this.successorActivityIdField = value;
            }
        }
        
        /// <remarks/>
        public string SuccessorActivityName {
            get {
                return this.successorActivityNameField;
            }
            set {
                this.successorActivityNameField = value;
            }
        }
        
        /// <remarks/>
        public int SuccessorActivityObjectId {
            get {
                return this.successorActivityObjectIdField;
            }
            set {
                this.successorActivityObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessorActivityObjectIdSpecified {
            get {
                return this.successorActivityObjectIdFieldSpecified;
            }
            set {
                this.successorActivityObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RelationshipSuccessorActivityType SuccessorActivityType {
            get {
                return this.successorActivityTypeField;
            }
            set {
                this.successorActivityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessorActivityTypeSpecified {
            get {
                return this.successorActivityTypeFieldSpecified;
            }
            set {
                this.successorActivityTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SuccessorFinishDate {
            get {
                return this.successorFinishDateField;
            }
            set {
                this.successorFinishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessorFinishDateSpecified {
            get {
                return this.successorFinishDateFieldSpecified;
            }
            set {
                this.successorFinishDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SuccessorProjectId {
            get {
                return this.successorProjectIdField;
            }
            set {
                this.successorProjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SuccessorProjectObjectId {
            get {
                return this.successorProjectObjectIdField;
            }
            set {
                this.successorProjectObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessorProjectObjectIdSpecified {
            get {
                return this.successorProjectObjectIdFieldSpecified;
            }
            set {
                this.successorProjectObjectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SuccessorStartDate {
            get {
                return this.successorStartDateField;
            }
            set {
                this.successorStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessorStartDateSpecified {
            get {
                return this.successorStartDateFieldSpecified;
            }
            set {
                this.successorStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SuccessorWbsName {
            get {
                return this.successorWbsNameField;
            }
            set {
                this.successorWbsNameField = value;
            }
        }
        
        /// <remarks/>
        public RelationshipType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public enum RelationshipPredecessorActivityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Dependent")]
        TaskDependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resource Dependent")]
        ResourceDependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level of Effort")]
        LevelofEffort,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Start Milestone")]
        StartMilestone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finish Milestone")]
        FinishMilestone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("WBS Summary")]
        WBSSummary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public enum RelationshipSuccessorActivityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Dependent")]
        TaskDependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resource Dependent")]
        ResourceDependent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level of Effort")]
        LevelofEffort,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Start Milestone")]
        StartMilestone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finish Milestone")]
        FinishMilestone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("WBS Summary")]
        WBSSummary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public enum RelationshipType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finish to Start")]
        FinishtoStart,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finish to Finish")]
        FinishtoFinish,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Start to Start")]
        StarttoStart,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Start to Finish")]
        StarttoFinish,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public partial class DeleteRelationshipsResponse {
        
        private bool returnField;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public partial class UpdateRelationshipsResponse {
        
        private bool returnField;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public partial class ReadRelationships {
        
        private RelationshipFieldType[] fieldField;
        
        private string filterField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public RelationshipFieldType[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Relationship/V1")]
    public enum RelationshipFieldType {
        
        /// <remarks/>
        Aref,
        
        /// <remarks/>
        Arls,
        
        /// <remarks/>
        CreateDate,
        
        /// <remarks/>
        CreateUser,
        
        /// <remarks/>
        IsPredecessorBaseline,
        
        /// <remarks/>
        IsPredecessorTemplate,
        
        /// <remarks/>
        IsSuccessorBaseline,
        
        /// <remarks/>
        IsSuccessorTemplate,
        
        /// <remarks/>
        Lag,
        
        /// <remarks/>
        LastUpdateDate,
        
        /// <remarks/>
        LastUpdateUser,
        
        /// <remarks/>
        ObjectId,
        
        /// <remarks/>
        PredecessorActivityId,
        
        /// <remarks/>
        PredecessorActivityName,
        
        /// <remarks/>
        PredecessorActivityObjectId,
        
        /// <remarks/>
        PredecessorActivityType,
        
        /// <remarks/>
        PredecessorFinishDate,
        
        /// <remarks/>
        PredecessorProjectId,
        
        /// <remarks/>
        PredecessorProjectObjectId,
        
        /// <remarks/>
        PredecessorStartDate,
        
        /// <remarks/>
        PredecessorWbsName,
        
        /// <remarks/>
        SuccessorActivityId,
        
        /// <remarks/>
        SuccessorActivityName,
        
        /// <remarks/>
        SuccessorActivityObjectId,
        
        /// <remarks/>
        SuccessorActivityType,
        
        /// <remarks/>
        SuccessorFinishDate,
        
        /// <remarks/>
        SuccessorProjectId,
        
        /// <remarks/>
        SuccessorProjectObjectId,
        
        /// <remarks/>
        SuccessorStartDate,
        
        /// <remarks/>
        SuccessorWbsName,
        
        /// <remarks/>
        Type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateRelationshipsCompletedEventHandler(object sender, CreateRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ReadRelationshipsCompletedEventHandler(object sender, ReadRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Relationship[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Relationship[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateRelationshipsCompletedEventHandler(object sender, UpdateRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateRelationshipsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateRelationshipsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DeleteRelationshipsCompletedEventHandler(object sender, DeleteRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteRelationshipsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteRelationshipsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591